import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ReactQuery from '../components/ReactQuery'
import NextAuthProvider from '@/components/NextAuthProvider'
import { Session } from "next-auth";
import { ReactNode } from 'react'
import LoadingPage from '@/components/LoadingPage'

const inter = Inter({ subsets: ['latin'] })

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, session
}: NextAuthProps) {
  return (
    <html lang="en">
      <body className={inter.className + 'px-4'}>
        <NextAuthProvider session={session}>
          <ReactQuery>
            <LoadingPage>
              {children}
            </LoadingPage>
          </ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  )
}
